In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [2, -3]])
w1, V1 = np.linalg.eig(A)

print(w1)
print(V1)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [3]:
A = np.array([[60., 30., 20.],
              [30., 20., 15.],
              [20., 15., 12.]])

w, V = np.linalg.eig(A)
w1, w2, w3 = w
v1 = V[:, 0:1]
v2 = V[:, 1:2]
v3 = V[:, 2:3]
A1 = v1 @ v1.T
A2 = v2 @ v2.T
A3 = v3 @ v3.T

In [4]:
w

array([84.49913563,  7.33962395,  0.16124042])

In [5]:
w1 * A1

array([[57.79768857, 32.13739648, 22.59357583],
       [32.13739648, 17.8694387 , 12.56276371],
       [22.59357583, 12.56276371,  8.83200836]])

In [6]:
w2 * A2

array([[ 2.19968372, -2.12270483, -2.60775134],
       [-2.12270483,  2.04841985,  2.51649195],
       [-2.60775134,  2.51649195,  3.09152039]])

In [7]:
w3 * A3

array([[ 0.00262772, -0.01469165,  0.01417551],
       [-0.01469165,  0.08214145, -0.07925566],
       [ 0.01417551, -0.07925566,  0.07647125]])

In [8]:
w1 * A1 + w2 * A2 + w3 * A3

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

붓꽃(Iris) 특징데이터 행렬 X의 분산행렬을 구하고 이 분산행렬의 고윳값들을 구하라.

In [10]:
from sklearn.datasets import load_iris

In [11]:
iris = load_iris()
X = iris.data
COV = X.T @ X
w , V = np.linalg.eig(COV)
w

array([9.20830507e+03, 3.15454317e+02, 1.19780429e+01, 3.55257020e+00])

행렬 A는 N개의 고윳값-고유벡터를 가진다(복소수인 경우와 중복인 경우를 포함).

행렬의 대각합은 모든 고윳값의 합과 같다.

행렬의 행렬식은 모든 고윳값의 곱과 같다.

행렬 A가 대칭행렬이면 N개의 실수 고윳값을 가지며 고유벡터들이 서로 **직교(orthogonal)**이다.

행렬 A가 대칭행렬이고 고윳값이 모두 양수이면 양의 정부호(positive-definite)이고 역행렬이 존재한다. 역도 성립한다.

행렬 A가 어떤 행렬 X의 분산행렬 XTX이면 0 또는 양의 고윳값을 가진다.

행렬 X∈RN×M(N≥M)가 풀랭크이면 분산행렬 XTX은 역행렬이 존재한다.