In [1]:
import numpy as np

# 놈(norm)

크기 및 절댓값으로 나타내 절댓값으로 일반화함

In [2]:
A = np.array([[1,1],[1,1]])
B=A@A
B

array([[2, 2],
       [2, 2]])

In [3]:
C=np.linalg.norm(B)
C*2

8.0

In [4]:
A.T@A

array([[2, 2],
       [2, 2]])

In [5]:
A = (np.arange(9) - 4).reshape((3, 3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [6]:
C=np.linalg.norm(A)
C*2

15.491933384829668

In [7]:
A.T@A

array([[21, 18, 15],
       [18, 18, 18],
       [15, 18, 21]])

In [8]:
A@A

array([[15,  6, -3],
       [ 6,  6,  6],
       [-3,  6, 15]])

In [9]:
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

# 대각합

대각합은 정방행렬에 대해서만 정의되며 대각원소의 합으로 계산된다.

In [21]:
A=np.array([[1],[1]])
B=np.array([[1,1],[1,1]])

C=A.T@B@A
D=B@A@A.T
E = A@A.T@B
print(C)
print(D)
print(E)

[[4]]
[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


In [18]:
np.trace(C)

4

In [20]:
np.trace(D)

4

In [22]:
np.trace(E)

4

In [23]:
A = np.array([[1,1],[1,1]])
A@A.T

array([[2, 2],
       [2, 2]])

In [24]:
np.trace(A)

2

# 행렬식

In [27]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
(A)

6.66133814775094e-16

In [32]:
B= np.array([[1, 2],[3, 4]])
B[0][0]*B[1][1] - B[0][1]*B[1][0]

-2

In [33]:
np.linalg.det(B)

-2.0000000000000004