선형 예측모형은 입력 데이터 벡터와 가중치 벡터의 내적으로 계산된 예측값이 실제 출력 데이터와 유사한 값을 출력하도록 하는 모형이다. 그럼 올바른 가중치 벡터는 어떻게 구할 수 있을까? 여기에서는 연립방정식과 역행렬을 이용하여 선형 예측모형의 가중치 벡터를 구하는 방법을 알아본다.

역행렬이 존재하는 행렬 : 가역행렬,정칙행렬,비특이행렬

역행렬이 존재하지 않는 행렬 : 비가역행렬,특이행렬,퇴화행렬

In [2]:
import numpy as np

In [3]:
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
np.linalg.det(A)

1.0

In [5]:
A.T

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 1]])

In [6]:
np.linalg.inv(A)

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

보스턴 집값 문제는 미국 보스턴내 각 지역(town)의 주택 가격을 그 지역의 범죄율이나 공기 오염도 등의 특징을 사용하여 예측하는 문제다. Scikit-Learn 패키지에서 임포트할 수 있다. 보스턴 집값 문제를 선형 예측모형 Ax=b^로 풀었을 때의 가중치 벡터 x를 구하라. 행렬과 벡터 데이터는 다음과 같이 얻을 수 있다. 여기에서는 문제를 간단하게 하기 위해 입력 데이터를 범죄율(CRIM), 공기 오염도(NOX), 방의 개수(RM), 오래된 정도(AGE)의 4종류로 제한했고 데이터도 4개만 사용했다.

In [7]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [8]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [11]:
b

array([24. , 21.6, 34.7, 33.4])

In [13]:
w=np.linalg.inv(A)@b
w

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

최소자승문제

In [14]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [15]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [16]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [17]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [18]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [19]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

D:\Anaconda\envs\minsu\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [20]:
resid, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.001666666666666655)

보스턴 집값 문제를 선형 예측모형 Xw=y^로 풀었을 때의 가중치벡터 w를 최소 자승 방법으로 구하라. 행렬과 벡터 데이터는 다음과 같이 얻을 수 있다.

In [21]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [22]:
x, resid, rank, s = np.linalg.lstsq(X, y)
x

D:\Anaconda\envs\minsu\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [23]:
X@x

array([29.09826353, 24.50227548, 31.22742641, 29.7071035 , 29.56479572,
       25.29376224, 21.53041161, 19.10333426, 11.09336136, 18.25932202,
       19.33401835, 20.4158837 , 19.66602494, 20.66457506, 20.52388857,
       20.11740519, 21.53034318, 18.36426279, 15.75504665, 18.82001911,
       13.36203016, 18.82895424, 17.8884165 , 15.26772521, 17.18318797,
       13.81345441, 16.64674785, 16.1607536 , 21.87232168, 23.39911229,
       12.92645767, 19.27385466, 10.60202091, 15.02702479, 14.86361453,
       22.55028082, 21.02570495, 22.07385902, 22.30111817, 31.18519291,
       34.74543406, 28.28052928, 24.25528702, 23.99006396, 21.95417691,
       20.13866996, 19.11701871, 17.61194914,  8.68504015, 16.00505355,
       20.25911735, 22.68849416, 27.11101246, 22.75668484, 17.51587049,
       33.2245068 , 25.77167394, 32.47529239, 22.47275348, 21.0195614 ,
       17.82761193, 18.56485243, 24.75749316, 24.84291605, 26.09941816,
       28.66957205, 23.27147714, 20.36659581, 16.49676624, 20.04

In [24]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21